### ISSUE TITLE
[COLIB-NGC] T1.1 update GovCT2

### ISSUE THREAD

**Issue by martinscripts** [CRESYM/colib0.github.io#169]
### Do you want to modify a model or test case?

- [X] Model
- [ ] Test Case

### What is the impact of modification to the model or test case?

- [X] minor
- [ ] moderate
- [ ] major

### Briefly describe the modification to the model/ test case

typo, folder structure

**Comment by martinscripts** [comment]
The main change is 
- a fix in the GovCT2 folder structure
- a suggested update to the folder structure for governors, avr and pss

please comment on whether you agree to this and/or have other suggestions. 

- please also note that i change d the names of the other Governor files, I think this improves readability in the overview. 
- if you agree, I can add the same alteration to the PSS and AVR names

**Comment by GJCRESYM** [comment]
Hi Marin, 

Could you please create the pull request to "dev" branch instead of main?

**Comment by martinscripts** [comment]
Hi @GJCRESYM, I changed base of the existing PRs, it should work now. BR

**Comment by GJCRESYM** [comment]
@ErwanGuichard49 , @martinscripts : The changes have been merged and are live on Colib.net. Please verify and let us know if any modifications are required. Thank you.

BR,
Geethu

**Comment by GJCRESYM** [comment]
Changes are merged to main
