### ISSUE TITLE
Capacitor bank 

### ISSUE THREAD

**Issue by Lampros-Cresym** [CRESYM/colib0.github.io#220]
### Specify the model/test case you evaluated

- [X] Model
- [ ] Testcase

### Name the model/test case ID, you would like to evaluate

0000

### What is the impact to the model or testcase?

- [X] minor
- [ ] moderate
- [ ] major

### Briefly describe your opinion about the model/testcase

We could generalize by also including reactor bank

**Comment by Carlos-Alegre** [comment]
Should we do a different page? Or just modify this one to be more general (i.e. Static Reactive Power Compensator model... or maybe shorter)?

**Comment by GJCRESYM** [comment]
Merged to main
