### ISSUE TITLE
[Evaluated]: ZIP load model

### ISSUE THREAD

**Issue by Lampros-Cresym** [CRESYM/colib0.github.io#224]
### Specify the model/test case you evaluated

- [X] Model
- [ ] Testcase

### Name the model/test case ID, you would like to evaluate

141

### What is the impact to the model or testcase?

- [X] minor
- [ ] moderate
- [ ] major

### Briefly describe your opinion about the model/testcase

I would remove this sentence: "The model does not take into account the time-response performance of the load, therefore it is not useful for dynamic studies."

**Comment by GJCRESYM** [comment]
Merged the changes into the main branch
