### ISSUE TITLE
[Evaluated]: Frequency Dependent Load Model

### ISSUE THREAD

**Issue by Lampros-Cresym** [CRESYM/colib0.github.io#225]
### Specify the model/test case you evaluated

- [X] Model
- [ ] Testcase

### Name the model/test case ID, you would like to evaluate

145

### What is the impact to the model or testcase?

- [X] minor
- [ ] moderate
- [ ] major

### Briefly describe your opinion about the model/testcase

- I would remove this sentence: "The model does not take into account the time-response performance of the load, therefore it is not useful for dynamic studies."
- Either k_p and k_q should have be in "1/Hz" unit or "Δf" should be replaced by "Δf/f_0"

**Comment by GJCRESYM** [comment]
Merged the changes into the main branch
