### ISSUE TITLE
Generic Phasor Grid Forming Voltage Source Converter

### ISSUE THREAD

**Issue by Lampros-Cresym** [CRESYM/colib0.github.io#229]
### Specify the model/test case you evaluated

- [X] Model
- [ ] Testcase

### Name the model/test case ID, you would like to evaluate

180

### What is the impact to the model or testcase?

- [ ] minor
- [X] moderate
- [ ] major

### Briefly describe your opinion about the model/testcase

- Is this model suitable for EMT or for phasor studies (or for both)? The title suggests that it is a phasor model, but Section 2 says that the model is for EMT studies
- Just to add a note that the VSM structure is not included in Fig. 1
- Would it be possible to add another section before the "open-source implementation" where we include: the tuning of the voltage control? This is just to clearly separate the tuning and the (proposed) plant model from the actual model of the VSC. I also propose to include in the end of the new section a table with all parameters and an indicative set of values.
- I am missing a clear description of how the current limitations are implemented. For example, how is the non-windup implemented? If you reach a current limit, which integrators have to be frozen? Otherwise, we should add a disclaimer in the model uses section because I am not sure we can simulate a fault with this model.

**Comment by Carlos-Alegre** [comment]
- That first paragraph is wrong, corrected.
- I included one of the possible implementations to obtain the frequency. It can be changed to be more general, add the VSM implementation, or just leave a comment saying it can be substituted with the preferred implementation, whichever works best.
-  We can comment this for all the models, we can maybe state the order of magnitude of the time constants and from there the other parameters of the model can be derived
-  Same as the previous point, we will add a current limitation block to explain in more detail this point, but we can discuss how to approach it.
