### ISSUE TITLE
Full-Phasor Grid Following Voltage Source Converter

### ISSUE THREAD

**Issue by Lampros-Cresym** [CRESYM/colib0.github.io#230]
### Specify the model/test case you evaluated

- [X] Model
- [ ] Testcase

### Name the model/test case ID, you would like to evaluate

163

### What is the impact to the model or testcase?

- [X] minor
- [ ] moderate
- [ ] major

### Briefly describe your opinion about the model/testcase

I only have limited comments here:
- typo: "... than the EMT without _loosing_ precision..."--> losing
- Some more explanation of how the limiters (non-windup, freezing, etc) would be useful.

**Comment by GJCRESYM** [comment]
Merged the changes into the main branch
