### ISSUE TITLE
GENTPF/GENTPJ Synchronous Machine with Saturation

### ISSUE THREAD

**Issue by Lampros-Cresym** [CRESYM/colib0.github.io#234]
### Specify the model/test case you evaluated

- [X] Model
- [ ] Testcase

### Name the model/test case ID, you would like to evaluate

196

### What is the impact to the model or testcase?

- [X] minor
- [ ] moderate
- [ ] major

### Briefly describe your opinion about the model/testcase

- Typo first paragraph of section 2: "later" --> "latter"
- Sub-section 3.1 - Parameters: It would be very nice to have a range of values for each parameter in the table
- Missing the definition of the $\omega_m$ and $Sat_q$ variables. In fact, I think that $\omega_m$ should be replaced simply by $\omega$ in all equations
- I think there is a mixup between the $Sat_d$ and $Sat_q$ variables in the $$dE''_q/dt$$ and $$dE''_d/dt$$ equations
- I think $X''_q$ should be replaced by $X''_d$ here
![image](https://github.com/user-attachments/assets/c06ac675-e193-4f06-8025-28479254306a)

**Comment by Carlos-Alegre** [comment]
Added suggested corrections. Pending adding ranges for the parameter table

**Comment by GJCRESYM** [comment]
@Carlos-Alegre : Are you working on this issue now? Do you have any branch created. If yes, could you please the branch to this issue. 

Thanks in advance

**Comment by Carlos-Alegre** [comment]
Done! I left it out when doing the PRs

**Comment by GJCRESYM** [comment]
Merged
