### ISSUE TITLE
GENQEC Synchronous Machine with Saturation

### ISSUE THREAD

**Issue by Lampros-Cresym** [CRESYM/colib0.github.io#235]
### Specify the model/test case you evaluated

- [X] Model
- [ ] Testcase

### Name the model/test case ID, you would like to evaluate

197

### What is the impact to the model or testcase?

- [X] minor
- [ ] moderate
- [ ] major

### Briefly describe your opinion about the model/testcase

- $\omega_m$ should either be replaced or defined in the variables
- It seems to me that Figure 1 in [2] does not have the same colours. Did you add the purple highlights? If yes, we should perhaps clarify why those parts are highlighted. Otherwise, could we simply have the same figures without any highlighted parts?

**Comment by GJCRESYM** [comment]
Merged the changes into the main branch.
