### ISSUE TITLE
[Others]:  a list of references appears in the "Others" page

### ISSUE THREAD

**Issue by Lampros-Cresym** [CRESYM/colib0.github.io#237]
### Specify the model/test case you evaluated

- [X] Model
- [ ] Testcase

### Name the model/test case ID, you would like to evaluate

0000

### What is the impact to the model or testcase?

- [ ] minor
- [X] moderate
- [ ] major

### Briefly describe your opinion about the model/testcase

A list of references appears (some are "dummy" references I guess).

To be removed

**Comment by GJCRESYM** [comment]
The issue is fixed and merged to main
