### ISSUE TITLE
[Bug]: Dead link to STEPSS model

### ISSUE THREAD

**Issue by Sciemon** [CRESYM/colib0.github.io#253]
### Is there an existing issue for this?

- [X] There are no existing issues

### Priority of this issue

- [ ] high
- [ ] medium
- [X] low

### What browsers are you seeing the problem on?

Firefox

### Describe the current behaviour

There is a dead link to the STEPSS model in the table at the bottom of this page:

https://colib.net/pages/testCases/converterDrivenStability/4VSCSystem/

**Comment by GJCRESYM** [comment]
Fixed the issue reported
