### ISSUE TITLE
Use of an ontology when creating article for models and test cases

### ISSUE THREAD

**Issue by matoubongrain** [CRESYM/colib0.github.io#27]
We would like to favour the use of a common langage and references to standard objects and definitions. 
A automatic module helping the writer of an article to create links to existing ontologies or standard object should be developed (autocompletion, automatic links to references, glossary constitution).
Best ways of implementing such solution hasn't been found so far...

**Comment by GJCRESYM** [comment]
It doesn't seem possible to do, no real ontology has been found and implementable. In the future, if possible, this issue could be reopened to implement the requirement.
