### ISSUE TITLE
fix dropdown menu 

### ISSUE THREAD

**Issue by matoubongrain** [CRESYM/colib0.github.io#3]
main menu isn't displayed correctly on the online version;

**Comment by promise-dash** [comment]
Could you please elaborate a little bit? Cuz I want to contribute and resolve this issue.
If you can share an image it would be of great help to understand the problem.

**Comment by matoubongrain** [comment]
Hello,
thanks a lot for your message, if you go on this webpage, you can see that
the dropdown menu isn't working:
https://cresym.github.io/colib0.github.io/
Feel free to propose any correction.
BR,
MB

**Comment by ECCresym** [comment]
This bug has been solved by adding the style.scss file.
