### ISSUE TITLE
Navigation side menu to be improved

### ISSUE THREAD

**Issue by matoubongrain** [CRESYM/colib0.github.io#42]
Current side menu for test cases and models automatically gets the titles and subtitles from the page content.
Improvements can be made on:
- this side menu should display only the main chapters, and scroll down menu for the subtitles. 
- the titles should be numbered instead of appearing as bullet points
- menu should be framed for clarity and placed correctly on the page
- page chapter titles and subtitles could reuse CRESYM logo colors

**Comment by GJCRESYM** [comment]
Fixed and implemented by Firas. Working as expected.
