### ISSUE TITLE
Improve model and test case templates

### ISSUE THREAD

**Issue by matoubongrain** [CRESYM/colib0.github.io#46]
- correct links to the template pages on deployed version 
- add an ID to model
- add a versioning table
- add a comment colum in the implementation table and a last date consulted.
- add description for each section and indicate if it is optinal or not
- add a link to the convention page (the page can be built based on the dynawo modelica nanimg convention https://github.com/dynawo/dynawo/blob/master/dynawo/sources/Models/Modelica/Dynawo/UsersGuide/NamingConventions.mo
- add a link to the tags page

**Comment by GJCRESYM** [comment]
Implemented and working as expected. 
Branch = 67_update_model_TS_templates
