### ISSUE TITLE
dead link leads to 404

### ISSUE THREAD

**Issue by martinscripts** [CRESYM/colib0.github.io#64]
Hey all! 
The link [How to contribute page](https://github.com/CRESYM/colib0.github.io/blob/main/about/contribute) in the [readme](https://github.com/CRESYM/colib0.github.io?tab=readme-ov-file) leads to the 404 page, seems like it hasn't been updated with the folder structure that includes /pages/.

BR!
.Martin

**Comment by GJCRESYM** [comment]
This issue is fixed and implemented. Working as expected.
